name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [23]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Blueprint Misti
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"

    - name: Install npm dependencies
      run: yarn install

    - name: Build
      run: |
        yarn build

    - name: Spellcheck code base
      run: |
        yarn spell

    - name: Run knip
      run: yarn knip

    - name: Check formatting with Prettier
      run: yarn fmt

    - name: Run ESLint
      run: yarn lint

    - name: Run tests
      run: yarn test

  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blueprint Misti
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: "yarn"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz
        # Install libffi7 coming as dependency of Souffle
        # wget http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
        # sudo dpkg -i libffi7_3.3-4_amd64.deb

    - name: Install Soufflé on Ubuntu
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo wget https://souffle-lang.github.io/ppa/souffle-key.public -O /usr/share/keyrings/souffle-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/souffle-archive-keyring.gpg] https://souffle-lang.github.io/ppa/ubuntu/ stable main" | sudo tee /etc/apt/sources.list.d/souffle.list
        sudo apt update
        sudo apt install souffle

    - name: Install npm dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run integration tests
      run: yarn blueprint-test
