name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [23]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Blueprint Misti
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"

    - name: Install npm dependencies
      run: yarn install

    - name: Build
      run: |
        yarn build

    - name: Spellcheck code base
      run: |
        yarn spell

    - name: Run knip
      run: yarn knip

    - name: Check formatting with Prettier
      run: yarn fmt

    - name: Run ESLint
      run: yarn lint

    - name: Run tests
      run: yarn test

